- symbol: GGAL.BA
  instrument_id: ISIN-AR-GGAL
  type: equity
  currency: ARS
  source: yfinance
- symbol: YPFD.BA
  instrument_id: ISIN-AR-YPFD
  type: equity
  currency: ARS
  source: yfinance
- symbol: PAMP.BA
  instrument_id: ISIN-AR-PAMP
  type: equity
  currency: ARS
  source: yfinance
- symbol: AAPL
  instrument_id: AAPL_US
  type: equity
  currency: USD
  source: tiingo
